---
title: "Estimating Role Strength in League of Legends"
author: "Caleb Kornfein"
date: "4/7/2022"
output: html_document
---

## 1 - Introduction
```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(caret)
library(gt)
library(arm)
library(MASS)
library(plotROC)
library(pROC)
library(broom)
library(knitr)
library(corrplot)
library(kableExtra)
library(RColorBrewer)
library(lemon)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r load}
df <- read.csv("Data_Creation/Data/final_ratio.csv")
```

### MODEL
```{r model}
df[,'OUTCOME'] <- factor(df[,'OUTCOME'])

m1 <- glm(OUTCOME ~ TOP_GOLD_RATIO + MIDDLE_GOLD_RATIO + JUNGLE_GOLD_RATIO + UTILITY_GOLD_RATIO + BOTTOM_GOLD_RATIO, data = df, family = "binomial")
m1
```

```{r formattting}
confidence <- as.data.frame(confint(m1))
m1_summary <- as.data.frame(coef(summary(m1)))
m1_summary$Lower <- confidence$"2.5 %"
m1_summary$Upper <- confidence$"97.5 %"
m1_summary$Estimate <- m1_summary$Estimate

rownames(m1_summary) <- c('Intercept', 'Top Gold Ratio', 'Middle Gold Ratio', 'Jungle Gold Ratio', 'Support Gold Ratio', 'Bottom Gold Ratio')
colnames(m1_summary) <- c('Estimate', 'Std. Error', 'Z-Score', 'P', 'Lower', 'Upper')

m1_summary <- m1_summary %>%
  mutate(P = case_when(P < 0.001 ~ "<0.001",
                       P < 1 ~ paste(format(round(P, digits=3), nsmall=3), sep=""))) %>%
  mutate(Estimate = format(round(Estimate, digits=3), nsmall=3)) %>%
  mutate(Lower = format(round(Lower, digits=3), nsmall=3)) %>%
  mutate(Upper = format(round(Upper, digits=3), nsmall=3))

colnames(m1_summary) <- c('Estimate', 'Std. Error', 'Z-Score', 'P-value', '2.5%', '97.5%')
m1_summary <- m1_summary[c('Estimate', '2.5%', '97.5%', 'P-value')]
```

```{r display}
m1_summary %>%
  kbl(caption = "",
      format="html",
      align="c",
      #row.names = FALSE,
      #col.names = c("Effect", "Adjusted* difference (95% CI) in mean postoperative eGFR","P-value"),
      escape = FALSE) %>%
  kable_classic(full_width = F, html_font = "Helvetica")
```


```{r diagnostics}
# CODE TAKEN FROM: http://www.sthda.com/english/articles/36-classification-methods-essentials/148-logistic-regression-assumptions-and-diagnostics-in-r/

predictors <- c('Top','Middle','Jungle','Support', 'Bottom')

small <- df[,c('TOP_GOLD_RATIO','MIDDLE_GOLD_RATIO','JUNGLE_GOLD_RATIO','UTILITY_GOLD_RATIO', 'BOTTOM_GOLD_RATIO')]

colnames(small) <- predictors

probabilities <- predict(m1, type = "response")

small <- small %>%
  mutate(logit = log(probabilities/(1-probabilities))) %>%
  gather(key = "predictors", value = "predictor.value", -logit)

ggplot(small, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + 
  theme_bw() + 
  labs(y = "Gold Ratio", x = "Predicted value (log odds)") +
  facet_wrap(~predictors, scales = "free_y")
```

 